language: python
python:
  - "3.6"
cache: pip
install:
  - pip install tox-travis coveralls
script:
  - tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: "bdist_wheel"
  user:
    secure: "W6fxAb3nY2REKS46n5+KW2cOJKEbtELZkp5HH90rubEEH7cK7R1a0oSJhvV5MLR+XhaWgvaMLfd6xERSA5PINMmYk3hOuQlIA7C2ulCZF1nQPpGBMmilXHlZljt2hOTfELlwQT9dHwZ3nrsktnMX0mPgnT9N1a+RnylQ1kPQFacSIX4DJ63Su9tFsP5tU7sp7KxhBzywIXQdSNRY/WeDd1faiCSxn1LPVkeZJ+ubOTyRGjAiIQsqEmO7vGs2AzgK0UpiiHEhzxGi6vle01NbDfib7nAQ2tglKqoeyJxLeSISLTfG024b/awMbBuzGf17Y1IevsH7aIreXqAGU1ARnxqLqeaObH03rhJcINSePRR1F0OMLsfvSugUCFCZJGmUEQgYXyEAaeTycI21C4TYMZNt/3f9hmwtSUtd54zd0XojtkwpwScY7b1dhGlxq//cXOAo6QBlUTPgkMHIDs5YMiOY6D8HltmjtdBR6Jb+/UKzLO2g0DkhaGPb/iOqFT/zFw7f2aEKyPp8hI41uNRoPmPPUpZZi9yA5xwskVARXZpEQiqSGvLoaAlM3jtH6QEUOCEm9Uw0W1vT7LtgNIMsJtFQfzK3mOQOjrAXauOUgDLIYBuT7JUYUxuC17V3AeTibXLLMKkPnbeLJckh7IjZM/cjopsoymIwu83b3Uq0wJA="
  password:
    secure: "G0XAKxXeCeZqYl2cp357VgWHIR+4R1u1+txwNR4N59cuw1eI8LFBlcEEvrQ6XIIBgGXcejhaSw9iSqAvKzEFfCPi0vmEFAGiN9o7vhMCjfhT6y0KbvljBlWYcvuet1ifgGCrJD9Rc8uN46gCKHYFA9axOLUW5yAF8/dYdo6NQcNcWkzTriAamygBOuvEs2K2V3AmQjurb6LalsJ5FRt6VIWjQ74DSi34Pru60HeAWY++7M45NVBSQ3eSDG1ABxD4H5QKv2pv8XZDldgNKLFKRFSP1uODRJMRJXTCM0fAmM5AGiVLzF/pyaUTT2Sp9DAkVZMx2OGBTIqr5Sy+a5zJEtzDXbJqadGuRACn/7woaLXibIbprKlnHHntSSvt8PQE9Q5DyA4dLO45oKRCVKX/Sdkgl/2/RG/nIGvKLmdr33flOXUuVRWQfH0KZhHyyojNa1u++ssQ8Wc4QiBK41CgHA+dIrMDJysY0BCZq11O2hoBZDC0KtNNPwnPPrmKlAsMfC9zx4VyGOlL0nnRkTiu+ZVChfXRbagpKKimEFWJRlLgItiMBgy0nByQS3Lzp6briKHB+uLEYZlDMkOzGrD2YC/fqKszBm3JwNBPz493l50w89kbH9wUU7ezqHA+99qv3oAlRYzHfmDlAOSqfxxaD1PSfMPVprW8u2swbZukixI="
  on:
    branch: master
  skip_existing: true
after_success:
- coveralls --verbose